root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  cmd = "go build -o ./tmp/frm cmd/dev_server/main.go"
  delay = 100
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_file = ["internal/db.go", "internal/models.go", "internal/sqlc_query.sql.go", "internal/copyfrom.go", "internal/queries.sql.go"]
  exclude_regex = ["_test.go", ".*_templ.go", ".*_enumer.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "templ", "html", "js", "css", "sql", "yaml" ]
  include_file = ["css/tailwind.css", "sqlc_query.sql", "sqlc.yaml"]
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = false
  keep_scroll = true
