// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package internal

import (
	"context"

	"github.com/acaloiaro/frm/types"
	uuid "github.com/google/uuid"
)

const getForm = `-- name: GetForm :one

SELECT id, workspace_id, name, fields, created_at, updated_at
FROM forms
WHERE workspace_id = $1
  AND id = $2
`

type GetFormParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	ID          int64     `json:"id"`
}

// GetForm
//
//	SELECT id, workspace_id, name, fields, created_at, updated_at
//	FROM forms
//	WHERE workspace_id = $1
//	  AND id = $2
func (q *Queries) GetForm(ctx context.Context, arg GetFormParams) (Form, error) {
	row := q.db.QueryRow(ctx, getForm, arg.WorkspaceID, arg.ID)
	var i Form
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Fields,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listForms = `-- name: ListForms :many

SELECT id, workspace_id, name, fields, created_at, updated_at
FROM forms
WHERE workspace_id = $1
`

// ListForms
//
//	SELECT id, workspace_id, name, fields, created_at, updated_at
//	FROM forms
//	WHERE workspace_id = $1
func (q *Queries) ListForms(ctx context.Context, workspaceID uuid.UUID) ([]Form, error) {
	rows, err := q.db.Query(ctx, listForms, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Form
	for rows.Next() {
		var i Form
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Fields,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveForm = `-- name: SaveForm :one

INSERT INTO forms (id, workspace_id, name, fields)
VALUES (coalesce(nullif($1, 0), nextval('form_ids'))::bigint, $2, $3, $4) ON conflict(id) DO
UPDATE
SET updated_at = timezone('utc', now()),
    name = $3,
    fields = $4 RETURNING id, workspace_id, name, fields, created_at, updated_at
`

type SaveFormParams struct {
	ID          interface{}      `json:"id"`
	WorkspaceID uuid.UUID        `json:"workspace_id"`
	Name        string           `json:"name"`
	Fields      types.FormFields `json:"fields"`
}

// SaveForm
//
//	INSERT INTO forms (id, workspace_id, name, fields)
//	VALUES (coalesce(nullif($1, 0), nextval('form_ids'))::bigint, $2, $3, $4) ON conflict(id) DO
//	UPDATE
//	SET updated_at = timezone('utc', now()),
//	    name = $3,
//	    fields = $4 RETURNING id, workspace_id, name, fields, created_at, updated_at
func (q *Queries) SaveForm(ctx context.Context, arg SaveFormParams) (Form, error) {
	row := q.db.QueryRow(ctx, saveForm,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Fields,
	)
	var i Form
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Fields,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
